services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: "./app-delivery-backend"
      dockerfile: Dockerfile
    env_file:
      - ./app-delivery-backend/.env
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - "./app-delivery-backend:/app"
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm install -g node && node src/db/create.ts && npm run start"

volumes:
  db_data:
